import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-organization-create',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './organization-create.component.html',
  styleUrls: ['./organization-create.component.css']
})
export class OrganizationCreateComponent {
  organizationForm: FormGroup;
  loading = false;
  error: string | null = null;
  success = false;
  selectedLogo: File | null = null;
  logoPreview: string | null = null;

  // Store generated credentials to display on screen
  generatedCredentials: {
    organizationName: string;
    username: string;
    password: string;
    email: string;
  } | null = null;

  private apiUrl = `${environment.apiUrl}/organizations`;

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
    private router: Router
  ) {
    this.organizationForm = this.fb.group({
      organizationName: ['', [Validators.required, Validators.minLength(2)]],
      organizationDescription: [''],
      contactEmail: ['', [Validators.email]],
      contactPhone: [''],
      address: [''],
      superAdminEmail: ['', [Validators.required, Validators.email]],
      superAdminFullName: ['', [Validators.required]]
      // Username and password will be auto-generated by the backend
    });
  }

  // Removed passwordMatchValidator - no longer needed since passwords are auto-generated

  onSubmit(): void {
    if (this.organizationForm.invalid) {
      this.markFormGroupTouched(this.organizationForm);
      return;
    }

    this.loading = true;
    this.error = null;

    const formData = { ...this.organizationForm.value };
    // Username and password will be auto-generated by backend

    this.http.post<any>(this.apiUrl, formData).subscribe({
      next: (response) => {
        console.log('✅ Organization created successfully:', response);

        // Store generated credentials to display on screen
        if (response.credentials) {
          this.generatedCredentials = {
            organizationName: response.organization?.name || formData.organizationName,
            username: response.credentials.username,
            password: response.credentials.password,
            email: formData.superAdminEmail
          };
        }

        // If logo is selected, upload it
        if (this.selectedLogo && response.organization?.id) {
          this.uploadLogo(response.organization.id);
        } else {
          this.success = true;
          this.loading = false;
          // Don't auto-redirect - let admin see and copy credentials
        }
      },
      error: (err) => {
        console.error('❌ Error creating organization:', err);
        this.error = err.error?.message || err.error?.error || 'Failed to create organization';
        this.loading = false;
      }
    });
  }

  onLogoSelected(event: any): void {
    const file = event.target.files[0];
    if (file) {
      // Validate file type
      if (!file.type.startsWith('image/')) {
        this.error = 'Please select an image file';
        return;
      }

      // Validate file size (max 5MB)
      if (file.size > 5 * 1024 * 1024) {
        this.error = 'Logo file size must be less than 5MB';
        return;
      }

      this.selectedLogo = file;
      this.error = null;

      // Create preview
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.logoPreview = e.target.result;
      };
      reader.readAsDataURL(file);
    }
  }

  removeLogo(): void {
    this.selectedLogo = null;
    this.logoPreview = null;
  }

  private uploadLogo(organizationId: number): void {
    if (!this.selectedLogo) {
      this.success = true;
      this.loading = false;
      return;
    }

    const formData = new FormData();
    formData.append('file', this.selectedLogo);

    this.http.post<any>(`${this.apiUrl}/${organizationId}/logo`, formData).subscribe({
      next: () => {
        console.log('✅ Logo uploaded successfully');
        this.success = true;
        this.loading = false;
      },
      error: (err) => {
        console.error('❌ Error uploading logo:', err);
        // Still show success for organization creation
        this.success = true;
        this.loading = false;
        this.error = 'Organization created but logo upload failed';
      }
    });
  }

  goToDashboard(): void {
    this.router.navigate(['/root/dashboard']);
  }

  private markFormGroupTouched(formGroup: FormGroup) {
    Object.keys(formGroup.controls).forEach(key => {
      const control = formGroup.get(key);
      control?.markAsTouched();
    });
  }

  cancel(): void {
    this.router.navigate(['/root/dashboard']);
  }

  getFieldError(fieldName: string): string {
    const field = this.organizationForm.get(fieldName);
    if (field?.touched && field?.errors) {
      if (field.errors['required']) return `${this.getFieldLabel(fieldName)} is required`;
      if (field.errors['email']) return 'Invalid email format';
      if (field.errors['minlength']) return `Minimum ${field.errors['minlength'].requiredLength} characters required`;
      if (field.errors['passwordMismatch']) return 'Passwords do not match';
    }
    return '';
  }

  private getFieldLabel(fieldName: string): string {
    const labels: { [key: string]: string } = {
      organizationName: 'Organization Name',
      organizationDescription: 'Description',
      contactEmail: 'Contact Email',
      contactPhone: 'Contact Phone',
      address: 'Address',
      superAdminUsername: 'Username',
      superAdminEmail: 'Email',
      superAdminFullName: 'Full Name',
      password: 'Password',
      confirmPassword: 'Confirm Password'
    };
    return labels[fieldName] || fieldName;
  }
}

